### PR TITLE
2.0.0

### LINKED ISSUE #10: glslify reformats source code, removes comments and whitespace
Is there any way to have glslify preserve the original source code formatting, including comments and whitespace? Switched from using gl-shader to glslify but now the shader code is less readable in Firefox's Shader Editor:

before:
screen shot 2014-05-27 at 7 14 04 pm

after:
screen shot 2014-05-27 at 7 14 24 pm

maybe preserve the original source if the browserify --debug option is passed? Or can you use Source Maps with GLSL?

### LINKED ISSUE #15: empty shader crashes
The following crashes when parsing:

```js
var createShader = glslify({
    inline: true,
    vertex: "void main() {}",
    fragment: "void main() {}",
});
```

```
// Unhandled stream error in pipe.
            ^
Error: expected `{`, got {}
{} at line 5
```

But putting a space inside the curly braces will fix it.

### LINKED ISSUE #21: uniform in vertex and fragment leads to extra uniform
If you have a uniform by the same name/type defined in both vertex and fragment, the resulting array of uniforms after glslify transform will have a duplicate entry:

```js
{
    vertex: ..
    fragment: ...
    uniforms: [
        { name: 'resolution', type: 'vec2' },
        { name: 'resolution', type: 'vec2' }
    ]
    ...
}
```

Not sure if intentional?

### LINKED ISSUE #25: Opening/closing spaces break require statements
e.g.:

``` glsl
#pragma glslify: noise = require( glsl-noise )
```

### LINKED ISSUE #30: use static-module
This might clean up the main static analysis code, not sure if there is anything particularly special that glslify needs.

https://www.npmjs.org/package/static-module

This would probably fix #28.

### LINKED ISSUE #31: glslify@2
There's a few kinks in glslify as it stands that I think would be best addressed with a significant reshuffle in the code, potentially a rewrite. It's probably a good idea to keep these changes in mind while we're writing the book chapter, seeing as it'll be a while before that's released and it'd be a shame if it were already out of date by then.

Here's what's on my radar:

* [ ] use [static-module](http://npmjs.org/package/static-module) (#30, #10) for static analysis.
* [ ] try and improve error handling. Perhaps the transform could log errors client-side instead of throwing/emitting errors during the build?
* [ ] default to `sourceOnly`, and leave it up to a hypothetical `glslify-shader` package to do the rest?
* [ ] more documentation.
* [ ] make the API more consistent between node, the CLI and the browser (#8).
* [ ] make it simpler to write framework-specific wrappers, and test this by writing framework-specific wrappers.
 * [ ] `glslify-three`
 * [ ] `glslify-pex`?
* [ ] better hooks to ease writing packages such as `glslify-live`, `glslify-api` and `glslify-optimize`.
* [ ] tests!
* [x] refactor internal packages to make sync APIs available:
 * [x] glsl-tokenizer
 * [x] glsl-parser
 * [x] glsl-deparser
* [ ] leave a window open for first-class functions, or at least callbacks (#23)

I don't see any need to change the require syntax or the package resolution, so those should remain untouched. The above changes mostly boil down to making glslify wizardry easier and loosening the coupling between glslify and the rest of the stack.gl ecosystem, giving it the chance to work just as well as a standalone tool.

If anybody would like to chime in with their thoughts on any of the above, please do!

### PR DESCRIPTION
**Pull request by hughsk**
The significant changes:

* Now more resistant to syntax errors, and can handle a lot of otherwise invalid GLSL. This allows us to have some fun with syntax in global transforms, e.g. to add first-class functions. There's still an issue causing the tokenizer to hang in some cases but that'll be fixed before this gets published.
* The browserify transform now only takes a single shader as input and returns a string. @mikolalysenko and I were chatting about this and think long-term it's the best way to go such that we don't lock anybody into using gl-shader by default.
* Token renaming via require pragmas behave differently now, which I still have to document.
* The guts of glslify bundling has been pulled out into [glslify-deps](http://github.com/stackgl/glslify-deps) and [glslify-bundle](http://github.com/stackgl/glslify-bundle). I might write up something that combines them in an easily reproducible fashion.

@stackgl/owners if you have any thoughts please feel free to weigh in! I'll be testing it on some existing apps tomorrow to ensure that nothing's broken but if you have apps using glslify it might be worth testing them too :)

Fixes #30
Fixes #31
Fixes #25 
Fixes #21 
Fixes #15 
Fixes #10

### CODE REVIEW

**Comment by mikolalysenko** [comment]
In terms of docs, it would be good to say a few words about glslify transforms and maybe something about inline shaders.

File: bin.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+})
+
+//
+// Build dependency tree, then output
+//
+if (argv._.length) {
+  return depper.add(argv._[0], output)
+}
+
+process.stdin.resume()
```
Comment (chrisdickinson) [inline bin.js]: I think the `.pipe` below *should* start flowing the `stdin` stream without `.resume()`.

File: index.js [hunk 2]
```diff
@@ -1,192 +1,89 @@
...
+    })
 
-      if(!node.arguments.length) {
-        return
-      }
+    // Extract and add our local transforms.
+    var transforms = opts.transform || []
+    ;(Array.isArray(transforms)
+      ?  transforms
+      : [transforms]
```
Comment (chrisdickinson) [inline index.js]: cool to just canonicalize `transform` as an array instead? (a la `transform = Array.isArray(transform) ? transform : [transform]`)?

File: bin.js [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+  input = src
+  depper.add(INPUT, output)
+}))
+
+//
+// Logs --help information out to stderr.
+//
+function help() {
+  fs.createReadStream(path.join(__dirname, 'usage.txt'))
+    .once('close', function() { console.error() })
```
Comment (chrisdickinson) [inline bin.js]: We may want to `process.exit(1)` here for bash scripts / makefile's sake.

**Comment by chrisdickinson** [comment]
Had a few comments + I need to look into the tokenizer renaming changes, but in general this looks good to me. Great work!

**Comment by kumavis** [comment]
awesome work :fire:

File: index.js (hunk 2 above)
Comment (hughsk) [inline index.js]: This is done more to ensure similarity with browserify's API – happy to change the style but think it should be possible to pass a single value :)

File: bin.js (hunk 3 above)
Comment (hughsk) [inline bin.js]: Good catch! :+1:

File: index.js (hunk 2 above)
Comment (chrisdickinson) [inline index.js]: Ah, I meant that to mean: assign `var transforms = opts.transform || []; transforms = Array.isArray(transforms) ? transforms : [transforms];` instead of introducing a one-off array on line 43. This also lets us avoid the leading semicolon, and `transforms` would always point to an array.

Comment (hughsk) [inline index.js]: Gotcha, sounds good :)

**Comment by mikolalysenko** [comment]
:fireworks: :fireworks: :tada:
